### ISSUE TITLE
NSFW Configuration Option

### ISSUE THREAD

**Issue by Daedalusspacegames** [Voxel-Fox-Ltd/Honey#1]
It would be nice to be able to configure Honey to disallow submitting NSFW characters (that is, remove the NSFW flow and options for submitting Sonas). I can imagine a use-case where someone wants to use Honey to keep track of Sonas but wants to maintain a SFW environment (yes, the moderator approval channel can theoretically accomplish this, but having the bot handle this would remove unnecessary workload from moderators). 

I've attempted to do this myself, but I've not had a lot of free time to put something together. If I end up with more free time and figure something out before this issue is closed, I'll happily upstream my code, but as it stands currently my attempt at implementing this is broken and incomplete.

**Comment by 4Kaylum** [comment]
What do you suggest for implementing this? What I have in my mind is removing the "is your sona NSFW question", removing the "approve as NSFW" button from modmail, and adding a "does your server allow NSFW content yes/no" to the server settings.

Am I missing anything?

**Comment by Daedalusspacegames** [comment]
There ought to be a check put in place to return an error if a user attempts to import an NSFW sona to a server with NSFW disallowed, otherwise, I believe you've covered everything.

**Comment by 4Kaylum** [comment]
I did think of that but at some point it's just easier to let moderators decline it rather than filtering it. It'd probably be pretty easy but I'll do that last if at all. 

On a less relevant note, where'd you see Honey's code from? It's only on 35 servers right now and still actively taking feedback before I list and advertise it.

**Comment by Daedalusspacegames** [comment]
I was trying to find a more up-to-date alternative to [ProfileBot](https://github.com/4Kaylum/ProfileBot), which I understand is an older project of yours. Honey is a more complete solution and closer to what I was looking for, compared to Profile, so I've been doing testing and looking to adapt it for a server I run.

**Comment by 4Kaylum** [comment]
Closed with 129f233f0f357eeb7d68983c6525cb062d35f4ec - importsona will filter out NSFW sonas, which is how I've chosen to do that. No error message or explanation will be shown, they'll just be silently filtered. Servers are NSFW by default.
